version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: liberfly-api-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
        - liberfly-api-test
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: liberfly-api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - liberfly-api-test

  api:
    build:
        args:
          user: admin
          uid: 1000
        context: ./
        dockerfile: Dockerfile
    image: liberfly_api_test
    depends_on:
      - db
      - nginx 
    container_name: liberfly-api-test
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - liberfly-api-test

networks:
  liberfly-api-test:
    driver: bridge

volumes:
  db:
    driver: local
  api:
    driver: local